version: '3.8'

services:
  zakony-ai:
    build: .
    container_name: zakony-ai
    ports:
      - "8501:8501"
    volumes:
      - ./temp_onedrive_data:/app/temp_onedrive_data
      - ./stiahnute_zakony:/app/stiahnute_zakony
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
